$(document).ready(function(){$(".Q a").click(function(){$(this).hasClass("true")?$(this).find("span").addClass("correct"):$(this).find("span").addClass("wrong");$(this).removeAttr("href");$(this).addClass("selected")});$("button span").click(function(){"Show Answer"==$(this).text()?$(this).text("Hide Answer"):"Hide Answer"==$(this).text()?$(this).text("Show Answer"):"Show Editor"==$(this).text()?$(this).text("Hide Editor"):"Hide Editor"==$(this).text()&&$(this).text("Show Editor")});(0<navigator.userAgent.indexOf("MSIE")||
0<navigator.userAgent.indexOf("Firefox"))&&$(".btn-test").click(function(){if($(this).find("a").attr("href")){var a=$(this).find("a").attr("href").replace("javascript:","");setTimeout(a,0)}})});function showAnswer(a){$("#A"+a).slideToggle("slow");$("#Q"+a+" .true").removeAttr("href");$("#Q"+a+" .true").addClass("selected");$("#Q"+a+" .true").find("span").addClass("correct")}function pad(a,c){for(var b=""+a;b.length<c;)b="0"+b;return b}
function formatTime(a){a/=10;var c=parseInt(a/6E3),b=parseInt(a/100)-60*c;a=pad(a-100*b-6E3*c,2);return(0<c?pad(c,2):"00")+":"+pad(b,2)+":"+a}var incrementTime=70,Timer=null,timeout=0;function updateTimer(){var a=formatTime(currentTime);$("#counter").html(a);0!=currentTime||timeout?(currentTime-=incrementTime,0>currentTime&&(currentTime=0)):finishTest()}
function finishTest(){Timer.stop();$("div.control").addClass("hide");$("#stage").html("");$("#stage").append("<a href='javascript:checkTestResult();' title='Check Result'><img src='/images/time_over.png' alt='Test is Over'/></a>");$("#stage").append("<center><a href='javascript:checkTestResult();' title='Check Result'><h2>Test is Over, Click Here to Check the Result</h2></a></center>");timeout=1;elapsedTime=givenTime-currentTime;$(".middle-col").attr("style","height:auto!important")}
function checkTestResult(){$.ajax({cache:!1,url:"checkTestResult.php",method:"POST",data:{testID:testID,testURL:testURL,questionMap:questionMap,totalQ:totalQ,elapsedTime:elapsedTime},success:function(a){$("#stage").html(a)}})}var selected=1;
function nextQuestion(a){0<timeout?alert("Given time for online test is over"):($(".Q a").each(function(a){$(this).hasClass("selected")&&(selected=1)}),selected?(null===Timer&&(Timer=$.timer(updateTimer,incrementTime,!0)),currentQ==totalQ?alert("You are already at last question"):(currentQ++,questionID=questionMap[currentQ].id,$("div.control").removeClass("hide"),$("#stage").load(a+"/"+questionID+".htm?QN="+currentQ,function(){selected=0;$("button").addClass("hide");10>questionMap[currentQ].selected&&
$(".Q a").each(function(a){questionMap[currentQ].selected===a&&($(this).addClass("selected"),selected=1)});$(".middle-col").height()<$(".sidebar").height()&&991<window.innerWidth&&$(".middle-col").css("height",$(".sidebar").height()+50);$(".middle-col").height()<$("#rightbar").height()&&991<window.innerWidth&&$(".middle-col").css("height","1113");$(".Q a").click(function(){var a=$(".Q a").index(this);questionMap[currentQ].selected=a;$(".Q a").each(function(a){$(this).hasClass("true")&&(questionMap[currentQ].correct=
a);$(this).removeClass("selected")});$(this).addClass("selected");selected=1});timeout&&($("#stage").html(""),$("#stage").append("<a href='javascript:checkTestResult();' title='Check Result'><img src='/images/time_over.png' alt='Time is Over'/></a>"),$("#stage").append("<center><a href='javascript:checkTestResult();' title='Check Result'><h2>Time is Over, Check Result</h2></a></center>"))}))):alert("Please select an asnwer before proceeding"))}
function previousQuestion(a){0<timeout?alert("Given time for online test is over"):(currentQ--,1>currentQ?(currentQ++,alert("You are already at first question!")):(questionID=questionMap[currentQ].id,$("div.pre-btn").removeClass("hide"),$("div.nxt-btn").removeClass("hide"),$("hr").removeClass("hide"),$("#stage").load(a+"/"+questionID+".htm?QN="+currentQ,function(){$("button").addClass("hide");10>questionMap[currentQ].selected&&$(".Q a").each(function(a){questionMap[currentQ].selected===a&&$(this).addClass("selected")});
$(".Q a").click(function(){var a=$(".Q a").index(this);questionMap[currentQ].selected=a;$(".Q a").each(function(a){$(this).hasClass("true")&&(questionMap[currentQ].correct=a);$(this).removeClass("selected")});$(this).addClass("selected")});timeout&&($("#stage").html(""),$("#stage").append("<a href='javascript:checkTestResult();' title='Check Result'><img src='/images/time_over.png' alt='Time is Over'/></a>"),$("#stage").append("<center><a href='javascript:checkTestResult();' title='Check Result'><h2>Time is Over, Check Result</h2></a></center>"))})))}
;